all: sort.c dirBranch.c funcPtr.c recursion.c
	gcc -std=c99 -m32 sort.c -o sort32
	gcc -std=c99 -m32 dirBranch.c -o dirBranch32
	gcc -std=c99 -m32 funcPtr.c -o funcPtr32
	gcc -std=c99 -m32 recursion.c -o recursion32
clean:
	rm *32
